global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'driftline'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api'
    static_configs:
      - targets: ['driftline-api:8000']
    metrics_path: '/metrics'

  - job_name: 'data-service'
    static_configs:
      - targets: ['driftline-data-service:8000']
    metrics_path: '/metrics'

  - job_name: 'drift-workers'
    static_configs:
      - targets: ['driftline-drift-worker:9090']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  - job_name: 'minio'
    static_configs:
      - targets: ['minio:9000']
    metrics_path: '/minio/v2/metrics/cluster'
